# Heavily influenced by https://github.com/aggregateknowledge/postgresql-hll/blob/master/.travis.yml

language: c

env:
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6

before_script:
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -sc`-pgdg main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - apt-cache search postgresql-server-dev
  - sudo apt-get install postgresql-${PGVERSION}
  - sudo apt-get install postgresql-server-dev-${PGVERSION}
  - export PATH=/usr/lib/postgresql/${PGVERSION}/bin:$PATH
  - sudo /etc/init.d/postgresql start ${PGVERSION}             # Start the version of PG that we want

script:
  - make
  - sudo make install
  - make installcheck

after_failure:
  - find . -name regression.out -exec cat '{}' \;
  - find . -name regression.diffs -exec cat '{}' \;

